### ISSUE TITLE
Bounding box difference? 

### ISSUE THREAD

**Issue by apple2373** [leetenki/YOLOv2#1]
Bounding boxがオリジナルのdarknetのものより小さめに出る気がするのですが、何かコメントありますか？

**Comment by leetenki** [comment]
えっと、darknetの訓練済み重みファイルをchainerで読み込んで実行するところですよね！
オリジナルでは、入力画像を無理やり一定の大きさ(例えば416 x 416)にリサイズしてからモデル入力しているのですが、自分の実装はできるだけ元画像のアスペクト比を維持した状態(例えば320 x 480等)でリサイズした後にモデル入力しています。このほうがもう少し精度上がるかなと色々実験していたので、コメント漏れてましたね。

https://github.com/leetenki/YOLOv2/blob/master/yolov2_darknet_predict.py#L32
この行のコメントアウトをはずして、その次の行をコメントアウトすれば、オリジナルに近い条件で実行できると思います。

**Comment by apple2373** [comment]
返事ありがとうございます。はい、YOLOでtrainしたものを移植した時の話です。変更してみたところ、オリジナルに近づきました。
