### ISSUE TITLE
problem in yolov2_darknet_parser.py

### ISSUE THREAD

**Issue by amazarashi** [leetenki/YOLOv2#10]
when I was executing  
`python yolov2_darknet_parser.py yolo.weights`

I had a error like,
```
File "yolov2_darknet_parser.py", line 87, in <module>
    exec(txt)
  File "<string>", line 1, in <module>
ValueError: cannot reshape array of size 12265129 into shape (1024,3072,3,3)
```

Is the model construction  correct ?

**Comment by wuwuwuxxx** [comment]
same issue, it seems like the darknet change the its weights

**Comment by amazarashi** [comment]
yo can get weight file from here
[link](https://drive.google.com/drive/folders/0B1tW_VtY7onidEwyQ2FtQVplWEU)

you should choose yolo.weights
