### ISSUE TITLE
Train on Deepfashion dataset. Why are the loss increase to be NaN during training?

### ISSUE THREAD

**Issue by Paul0M** [leetenki/YOLOv2#21]
Original yolov2_train.py is based on images generated by merging foreground and background.
and the darknet19_train.py has only image classification.
And now, I wanna train yolov2 with Deepfashion Dataset with bbox. 
I've made a image_generate script to output data, t.    
              

- data is the numpy array of an image;    

- t is the **x,y,w,h,label** for the data.

My chainer version is 4.
Also, delete the test = ... in yolov2.py (such as line 92), and use with chainer.using_config('train', True) in the yolov2_train.py, and with `x, t = generate_samples(n_samples=1, width=input_width,height=input_height)`
to generate 1 sample to debug.
comment out the debug_print.
During batch 1, everything's fine. but during batch 2, the self.conv1(x) will output NaN while x has real values. 
My guess is the the W for conv1 is too large, but I can't verify it. 

Has anyone encountered this problem? It'll be very kind that you guys can give me some hints.

The dataset I use is **In-shop Clothes Retrieval Benchmark** [http://mmlab.ie.cuhk.edu.hk/projects/DeepFashion.html](url), just upper-body, lower-body, full-body, 3 classes.

Here is the screen shot.
![1219_3](https://user-images.githubusercontent.com/13173000/34137862-ea83c380-e4a7-11e7-877d-c4167bacae3f.png)

Here are the corresponding file

[YS_YOLOv2.zip](https://github.com/leetenki/YOLOv2/files/1570120/YS_YOLOv2.zip)

**Comment by Paul0M** [comment]
solved

**Comment by uu-asd** [comment]
I'm also getting similar issue can you tell me how you solved ?

**Comment by yuma116** [comment]
I have the same problem.
Please tell me how you solved it.
